import type { PoopEntry, PoopId } from '@/types';

export const POOP_ENCYCLOPEDIA: Record<PoopId, PoopEntry> = {
  normal: {
    id: 'normal',
    name: 'ノーマルうんち',
    emoji: '💩',
    rarity: 1,
    scoreMultiplier: 1,
    description: 'いちばん よくでる ふつうの うんち。まきまき 3だんの クラシックな かたち！',
    hint: 'ふつうに れんだ してみよう',
    color: 0x8B4513,
  },
  tiny: {
    id: 'tiny',
    name: 'ちびうんち',
    emoji: '💩',
    rarity: 1,
    scoreMultiplier: 1,
    description: 'ちいさくて かわいい うんち。もうちょっと がんばろう！',
    hint: 'あまり ボタンを おさないと でるよ',
    color: 0x8B4513,
  },
  long: {
    id: 'long',
    name: 'ながーいうんち',
    emoji: '🐍',
    rarity: 2,
    scoreMultiplier: 2,
    description: 'ヘビみたいに ながーい うんち。リズムよく だすと できるよ！',
    hint: 'いちていの リズムで れんだ しよう',
    color: 0x6B3410,
  },
  thick: {
    id: 'thick',
    name: 'ぶっというんち',
    emoji: '🪨',
    rarity: 2,
    scoreMultiplier: 2,
    description: 'ふとくて どっしり した うんち。ちからづよさが でてるね！',
    hint: 'ゆっくり ちからづよく おしてみよう',
    color: 0x4E2A04,
  },
  softServe: {
    id: 'softServe',
    name: 'ソフトクリームうんち',
    emoji: '🍦',
    rarity: 3,
    scoreMultiplier: 3,
    description: 'ソフトクリームみたいに きれいな まきまき！ おいしそう…？',
    hint: 'とても あんていした リズムで れんだ しよう',
    color: 0xD2B48C,
    secondaryColor: 0x8B4513,
  },
  pebble: {
    id: 'pebble',
    name: 'つぶつぶうんち',
    emoji: '🫘',
    rarity: 3,
    scoreMultiplier: 3,
    description: 'ころころ つぶつぶの うんち。いっぱい でたね！',
    hint: 'バラバラな リズムで おしてみよう',
    color: 0x6B3410,
  },
  fluffy: {
    id: 'fluffy',
    name: 'もこもこうんち',
    emoji: '☁️',
    rarity: 3,
    scoreMultiplier: 3,
    description: 'くもみたいに もこもこ した うんち。ふわっふわ！',
    hint: '2かい おして やすんで、を くりかえそう',
    color: 0xBC8F6F,
  },
  rainbow: {
    id: 'rainbow',
    name: 'カラフルうんち',
    emoji: '🌈',
    rarity: 4,
    scoreMultiplier: 5,
    description: 'にじいろに かがやく うんち！すごい スピードの しょうこ！',
    hint: 'ものすごく はやく れんだ しよう',
    color: 0xFF0000,
    secondaryColor: 0x0000FF,
  },
  golden: {
    id: 'golden',
    name: 'ゴールデンうんち',
    emoji: '✨',
    rarity: 4,
    scoreMultiplier: 5,
    description: 'きんいろに ぴかぴか ひかる うんち！おかねもち に なれるかも！？',
    hint: 'だんだん はやく れんだ してみよう',
    color: 0xFFD700,
    secondaryColor: 0xDAA520,
  },
  star: {
    id: 'star',
    name: 'ほしのうんち',
    emoji: '⭐',
    rarity: 5,
    scoreMultiplier: 10,
    description: 'おほしさまの かたちの でんせつの うんち！きみは うんちマスター だ！',
    hint: 'あんていリズム + さいごに ながおし してみよう',
    color: 0xFFEB3B,
    secondaryColor: 0xFFF176,
  },
};

export const POOP_IDS: PoopId[] = [
  'normal', 'tiny', 'long', 'thick', 'softServe',
  'pebble', 'fluffy', 'rainbow', 'golden', 'star',
];
